//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.29 at 02:40:16 PM CEST 
//


package org.springframework.samples.petclinic.soap.owner;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.springframework.samples.petclinic.soap.owner package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.springframework.samples.petclinic.soap.owner
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetOwnersRequest }
     * 
     */
    public GetOwnersRequest createGetOwnersRequest() {
        return new GetOwnersRequest();
    }

    /**
     * Create an instance of {@link FindOwnersRequest }
     * 
     */
    public FindOwnersRequest createFindOwnersRequest() {
        return new FindOwnersRequest();
    }

    /**
     * Create an instance of {@link UpdateOwnerResponse }
     * 
     */
    public UpdateOwnerResponse createUpdateOwnerResponse() {
        return new UpdateOwnerResponse();
    }

    /**
     * Create an instance of {@link FindOwnersResponse }
     * 
     */
    public FindOwnersResponse createFindOwnersResponse() {
        return new FindOwnersResponse();
    }

    /**
     * Create an instance of {@link Owner }
     * 
     */
    public Owner createOwner() {
        return new Owner();
    }

    /**
     * Create an instance of {@link GetOwnerResponse }
     * 
     */
    public GetOwnerResponse createGetOwnerResponse() {
        return new GetOwnerResponse();
    }

    /**
     * Create an instance of {@link GetOwnerRequest }
     * 
     */
    public GetOwnerRequest createGetOwnerRequest() {
        return new GetOwnerRequest();
    }

    /**
     * Create an instance of {@link GetOwnersResponse }
     * 
     */
    public GetOwnersResponse createGetOwnersResponse() {
        return new GetOwnersResponse();
    }

    /**
     * Create an instance of {@link AddOwnerResponse }
     * 
     */
    public AddOwnerResponse createAddOwnerResponse() {
        return new AddOwnerResponse();
    }

    /**
     * Create an instance of {@link AddOwnerRequest }
     * 
     */
    public AddOwnerRequest createAddOwnerRequest() {
        return new AddOwnerRequest();
    }

    /**
     * Create an instance of {@link UpdateOwnerRequest }
     * 
     */
    public UpdateOwnerRequest createUpdateOwnerRequest() {
        return new UpdateOwnerRequest();
    }

}
