//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.29 at 02:40:16 PM CEST 
//


package org.springframework.samples.petclinic.soap.pet;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.springframework.samples.petclinic.soap.pet package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.springframework.samples.petclinic.soap.pet
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddPetRequest }
     * 
     */
    public AddPetRequest createAddPetRequest() {
        return new AddPetRequest();
    }

    /**
     * Create an instance of {@link Pet }
     * 
     */
    public Pet createPet() {
        return new Pet();
    }

    /**
     * Create an instance of {@link UpdatePetRequest }
     * 
     */
    public UpdatePetRequest createUpdatePetRequest() {
        return new UpdatePetRequest();
    }

    /**
     * Create an instance of {@link GetPetsResponse }
     * 
     */
    public GetPetsResponse createGetPetsResponse() {
        return new GetPetsResponse();
    }

    /**
     * Create an instance of {@link GetPetRequest }
     * 
     */
    public GetPetRequest createGetPetRequest() {
        return new GetPetRequest();
    }

    /**
     * Create an instance of {@link GetPetTypesResponse }
     * 
     */
    public GetPetTypesResponse createGetPetTypesResponse() {
        return new GetPetTypesResponse();
    }

    /**
     * Create an instance of {@link PetType }
     * 
     */
    public PetType createPetType() {
        return new PetType();
    }

    /**
     * Create an instance of {@link GetPetsRequest }
     * 
     */
    public GetPetsRequest createGetPetsRequest() {
        return new GetPetsRequest();
    }

    /**
     * Create an instance of {@link GetPetResponse }
     * 
     */
    public GetPetResponse createGetPetResponse() {
        return new GetPetResponse();
    }

    /**
     * Create an instance of {@link UpdatePetResponse }
     * 
     */
    public UpdatePetResponse createUpdatePetResponse() {
        return new UpdatePetResponse();
    }

    /**
     * Create an instance of {@link GetPetTypesRequest }
     * 
     */
    public GetPetTypesRequest createGetPetTypesRequest() {
        return new GetPetTypesRequest();
    }

    /**
     * Create an instance of {@link AddPetResponse }
     * 
     */
    public AddPetResponse createAddPetResponse() {
        return new AddPetResponse();
    }

}
