//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.30 at 01:43:50 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://petclinic.samples.springframework.org/soap/pet", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.springframework.samples.petclinic.soap.pet;
